config/routes.rb
Rails.application.routes.draw do

  post 'cart/add'

  ActiveAdmin.routes(self)
  devise_for :users

  root 'home#index'

  get 'meal/:id', to:'home#show_meal', as: 'show_meal'
  get 'restaurant/:id', to:'home#show_restaurant', as: 'show_restaurant'

end

app/models/adapters/only_admins.rb
class Adapters::OnlyAdmins < ActiveAdmin::AuthorizationAdapter

  def authorized?(action, subject = nil)
    user.admin?
  end

end

app/models/meal.rb
class Meal < ActiveRecord::Base
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :meals
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:name, :phone, :address]
  end

  def access_denied(exception)
    flash[:danger] = exception.message
    redirect_to root_url
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  def add
    #Возможно это нужно вынести в метод, и вызывать в before acction, чтобы session[:cart] всегда существовало
    unless session[:cart]
      session[:cart] = []
    end

    session[:cart].push params[:meal]

    redirect_to :back
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show_meal
    @meal = Meal.find(params[:id])
  end

  def show_restaurant
    @restaurant = Restaurant.find(params[:id])
    @meals = Meal.where(restaurant_id: @restaurant.id)
    unless session[:cart]
      session[:cart] = []
    end

    @items = Meal.find(session[:cart])
    @cart_items = []
    @items.each do |meal|
      if meal.restaurant == @restaurant
        @cart_items.push meal
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/cart/_cart.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Cart
  </div>
  <div class="panel-body">
    <% total_price = 0 %>
    <% if @cart_items.count > 0 %>
        <table class="table table-condensed">
          <% @cart_items.each do |meal| %>
              <% quantity = session[:cart].count(meal.id.to_s)%>
              <tr>
                <td><%= meal.name %></td>
                <td> x </td>
                <td> <%= quantity %></td>
                <td><%= meal.price * quantity %></td>
              </tr>
              <% total_price += (meal.price * quantity) %>
          <% end %>
          <tr>
            <td>Total:</td>
            <td></td>
            <td><%= total_price %></td>
            <td>soms</td>
          </tr>
        </table>
    <% else %>
        <p>There are no items in your cart</p>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-12">
  <% @restaurants.each do |restaurant| %>
      <div class="col-md-4 col-sm-6">
        <div class="restaurant">
          <%= link_to (image_tag "/uploads/restaurants/#{restaurant.image}"),
                      show_restaurant_path(restaurant)%>
          <%= restaurant.name %>
          <%= restaurant.description %>
        </div>
      </div>
  <% end %>
</div>

app/views/home/show_meal.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="div">
      <%= image_tag "/uploads/meals/#{@meal.image}", style:"max-width:100%" %>
    </div>

  </div>
  <div class="col-md-6">
    <h2><%= @meal.name %></h2>
    <strong><%= @meal.price %></strong>
    <div class="well">
      <p><%= @meal.description %></p>
    </div>
  </div>
</div>

<div class="row">

</div>

app/views/home/show_meals.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Meals</h1>

<table class="table table-hover">
  <thead>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Description</th>
    <th>Restaurant</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @meals.each do |meal| %>
      <tr>
        <td><%= meal.name %></td>
        <td><%= meal.price %></td>
        <td><%= meal.description %></td>
        <td><%= meal.restaurant.name %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/home/show_restaurant.html.erb
<div class="row">
  <div class="col-md-3">
    <%= image_tag "/uploads/restaurants/#{@restaurant.image}", class:"res-image" %>
  </div>
  <div class="col-md-6">
    <h1><%= @restaurant.name %></h1>
    <div class="well">
      <p><%= @restaurant.description %></p>
    </div>
  </div>
  <div class="col-md-3">
    <%= render 'cart/cart' %>
  </div>
</div>

<hr/>

<div class="row">
  <% @meals.each do |meal| %>
      <div class="col-xs-6 col-md-3">
        <div class="meal-block">
          <%= link_to (image_tag "/uploads/meals/#{meal.image}", class:"thumbnail meal-image"), show_meal_path(meal)%>
          <caption>
            <h3><%= meal.name %></h3>
            <p><strong><%= meal.price %></strong></p>
            <%= link_to "Add to Cart", cart_add_path(meal: meal), method: :post,
                                    class:"btn btn-add-cart"%>
          </caption>
        </div>
      </div>
  <% end %>
</div>

app/views/home/show_restaurants.html.erb
<h1>Listing Restaurants</h1>

<table class="table table-hover">
  <thead>
  <tr>
    <th>Image</th>
    <th>Name</th>
    <th>Description</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%=image_tag "/uploads/restaurants/#{restaurant.image}", height:'80'%></td>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.description %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NambaFood</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'NambaFood', root_path, class:"navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

      </ul>
      <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
            <p class="navbar-text">
              <span class="glyphicon glyphicon-star" aria-hidden="true"></span> Hello, <%= link_to current_user.name%>
            </p>
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            </ul>
        <% else %>
            <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
            <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>
</body>

</html>